# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_time',
            new_name='approved_comment',
        ),
    ]
